name: Publish on GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci
      - run: npm run build
      - run: npx @marp-team/marp-cli@latest ./examples/slides.md --theme ./dist/nord.css --config ./examples/marp.config.js --output ./examples/dist/index.html

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.0.1
        with:
          build_dir: ./examples/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
