name: Publish on GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build slides
        run: deno task --cwd ./examples marp ./slides.md --config-file ./marp.config.mjs --output ../dist/slides.html

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.0.1
        with:
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
